
import SimpleInput from './components/SimpleInput'

// FORM VALIDATION USUALLY REVOLVES AROUND THREE APPROACHES:
// 1. VALIDATE AFTER SUBMIT (POOR UX, GOOD STATE MANAGEMENT)
// 2. VALIDATE KEYSTROKES (POOR STATE MANAGEMENT IF MULTIPLE INSTANCES, GOOD UX)
// 3. VALIDATE ON BLUR (BEST OF ALL WORLDS IN MOST CASES)

// YOU CAN GRAB VALUES THROUGH STATE MANAGEMENT OR REFS.
// EITHER IS FINE BUT SETTING VALUES THROUGH REFS IS A BAD DECISION.
// THIS EXAMPLE USES STATE TO APPROACH GET/SET VALUES IN FORMS.

// 3 PIECES OF STATE NORMALLY USED TO LOOK AT VALIDITY:
// 1. THE VALUE
// 2. VALIDATION STATUS? (Y/N)
// 3. TOUCHED ELEMENT? (Y/N)

function App() {
  return (
    <div className="app">
      <SimpleInput />
    </div>
  )
}

export default App
